# Generated by Django 4.2.16 on 2026-04-07 12:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import scheduling.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DutyGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('join_code', models.CharField(default=scheduling.models.generate_code, editable=False, max_length=10, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duty_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DutyGroupMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('duty_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='scheduling.dutygroup')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duty_group_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-joined_at'],
            },
        ),
        migrations.AddField(
            model_name='dutygroup',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='joined_duty_groups', through='scheduling.DutyGroupMembership', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='dutygroupmembership',
            constraint=models.UniqueConstraint(fields=('duty_group', 'student'), name='unique_duty_group_membership'),
        ),
        migrations.AddConstraint(
            model_name='dutygroup',
            constraint=models.UniqueConstraint(fields=('instructor', 'name'), name='unique_duty_group_name_per_instructor'),
        ),
    ]
